package adif

import "testing"

func TestParseAll(t *testing.T) {
	tests := []struct {
		name string
		in   string
		want []Record
	}{
		{
			name: "header skipped, one record",
			in:   "Generated by X\n<ADIF_VER:5>3.1.0<PROGRAMID:1>X<EOH>\n<CALL:5>W1AW <BAND:3>20M<MODE:3>SSB<EOR>\n",
			want: []Record{{"CALL": "W1AW ", "BAND": "20M", "MODE": "SSB"}},
		},
		{
			name: "no header, multiple records",
			in:   "<CALL:4>3Y0J<DXCC:2>24<EOR><CALL:4>W1AW<DXCC:3>291<STATE:2>CT<EOR>",
			want: []Record{{"CALL": "3Y0J", "DXCC": "24"}, {"CALL": "W1AW", "DXCC": "291", "STATE": "CT"}},
		},
		{
			name: "type suffix ignored",
			in:   "<CALL:5:S>K1ABC<FREQ:6:N>14.074<EOR>",
			want: []Record{{"CALL": "K1ABC", "FREQ": "14.074"}},
		},
		{
			name: "value containing spaces and newline (length-delimited)",
			in:   "<COMMENT:11>line1\nline2x<EOR>",
			want: []Record{{"COMMENT": "line1\nline2"}},
		},
		{
			name: "lowercase tag names uppercased",
			in:   "<call:4>W1AW<band:3>40m<eor>",
			want: []Record{{"CALL": "W1AW", "BAND": "40m"}},
		},
		{
			name: "final record without trailing EOR is tolerated",
			in:   "<CALL:4>W1AW<DXCC:3>291",
			want: []Record{{"CALL": "W1AW", "DXCC": "291"}},
		},
		{
			name: "zero-length field",
			in:   "<CALL:4>W1AW<STATE:0><EOR>",
			want: []Record{{"CALL": "W1AW", "STATE": ""}},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got, err := ParseAll(tt.in)
			if err != nil {
				t.Fatalf("ParseAll error: %v", err)
			}
			if len(got) != len(tt.want) {
				t.Fatalf("got %d records, want %d: %#v", len(got), len(tt.want), got)
			}
			for i := range tt.want {
				for k, v := range tt.want[i] {
					if got[i][k] != v {
						t.Errorf("record %d field %q = %q, want %q", i, k, got[i][k], v)
					}
				}
				if len(got[i]) != len(tt.want[i]) {
					t.Errorf("record %d has %d fields, want %d: %#v", i, len(got[i]), len(tt.want[i]), got[i])
				}
			}
		})
	}
}

func TestRecordGet(t *testing.T) {
	r := Record{"STATE": "  CT  "}
	if got := r.Get("STATE"); got != "CT" {
		t.Errorf("Get trimmed = %q, want CT", got)
	}
	if got := r.Get("MISSING"); got != "" {
		t.Errorf("Get missing = %q, want empty", got)
	}
}
